// 从 dev-toolbox src/data/reference.ts 同步；改数据时两边一起改。
export interface LinuxCommand {
  cmd: string;
  zh: string;
  eg: string;
}

export const linuxCommands: LinuxCommand[] = [
  { cmd: "ls", zh: "列出目录内容", eg: "ls -alh" },
  { cmd: "cd", zh: "切换目录", eg: "cd /var/log" },
  { cmd: "pwd", zh: "显示当前路径", eg: "pwd" },
  { cmd: "cp", zh: "复制文件/目录", eg: "cp -r src/ bak/" },
  { cmd: "mv", zh: "移动或重命名", eg: "mv a.txt b.txt" },
  { cmd: "rm", zh: "删除（-rf 不可恢复，慎用）", eg: "rm -i file.txt" },
  { cmd: "mkdir", zh: "创建目录", eg: "mkdir -p a/b/c" },
  { cmd: "rmdir", zh: "删除空目录", eg: "rmdir empty/" },
  { cmd: "touch", zh: "创建空文件 / 更新时间戳", eg: "touch app.log" },
  { cmd: "ln", zh: "创建链接", eg: "ln -s /opt/app/current link" },
  { cmd: "find", zh: "按条件查找文件", eg: "find . -name '*.log' -mtime +7" },
  { cmd: "locate", zh: "基于索引快速查找", eg: "locate nginx.conf" },
  { cmd: "which", zh: "查看命令所在路径", eg: "which python3" },
  { cmd: "whereis", zh: "查找命令的二进制/手册", eg: "whereis nginx" },
  { cmd: "file", zh: "识别文件类型", eg: "file archive.bin" },
  { cmd: "stat", zh: "查看文件详细元信息", eg: "stat -c %s file" },
  { cmd: "tree", zh: "树状显示目录", eg: "tree -L 2" },
  { cmd: "du", zh: "统计目录占用", eg: "du -sh * | sort -h" },
  { cmd: "df", zh: "查看磁盘剩余空间", eg: "df -h" },
  { cmd: "cat", zh: "输出文件内容", eg: "cat /etc/hosts" },
  { cmd: "less", zh: "分页查看（可搜索）", eg: "less +F app.log" },
  { cmd: "head", zh: "查看开头若干行", eg: "head -n 20 file" },
  { cmd: "tail", zh: "查看末尾 / 实时跟踪", eg: "tail -f app.log" },
  { cmd: "grep", zh: "按模式搜索文本", eg: "grep -rn 'TODO' src/" },
  { cmd: "sed", zh: "流式替换/编辑", eg: "sed -i 's/old/new/g' file" },
  { cmd: "awk", zh: "按列处理文本", eg: "awk -F: '{print $1}' /etc/passwd" },
  { cmd: "cut", zh: "按分隔符取列", eg: "cut -d, -f1,3 data.csv" },
  { cmd: "sort", zh: "排序", eg: "sort -u -n nums.txt" },
  { cmd: "uniq", zh: "相邻去重（常配合 sort）", eg: "sort file | uniq -c" },
  { cmd: "wc", zh: "统计行/词/字节数", eg: "wc -l file" },
  { cmd: "tr", zh: "字符替换或删除", eg: "tr 'a-z' 'A-Z'" },
  { cmd: "diff", zh: "比较两个文件差异", eg: "diff -u a.txt b.txt" },
  { cmd: "xargs", zh: "把输入转为命令参数", eg: "find . -name '*.tmp' | xargs rm" },
  { cmd: "tee", zh: "同时输出到屏幕与文件", eg: "cmd | tee out.log" },
  { cmd: "ps", zh: "查看进程快照", eg: "ps aux | grep nginx" },
  { cmd: "top", zh: "实时进程与负载监控", eg: "top -o %CPU" },
  { cmd: "htop", zh: "更友好的进程监控", eg: "htop" },
  { cmd: "kill", zh: "按 PID 发送信号", eg: "kill -9 12345" },
  { cmd: "pkill", zh: "按名称结束进程", eg: "pkill -f node" },
  { cmd: "bg", zh: "把任务放到后台", eg: "bg %1" },
  { cmd: "fg", zh: "把后台任务调回前台", eg: "fg %1" },
  { cmd: "jobs", zh: "查看当前 shell 的后台任务", eg: "jobs -l" },
  { cmd: "nohup", zh: "脱离终端运行", eg: "nohup ./run.sh &" },
  { cmd: "systemctl", zh: "管理 systemd 服务", eg: "systemctl restart nginx" },
  { cmd: "journalctl", zh: "查看 systemd 日志", eg: "journalctl -u nginx -f" },
  { cmd: "service", zh: "旧版服务管理", eg: "service mysql status" },
  { cmd: "crontab", zh: "定时任务", eg: "crontab -e" },
  { cmd: "at", zh: "一次性定时任务", eg: "echo ls | at 09:00" },
  { cmd: "chmod", zh: "修改权限", eg: "chmod 755 script.sh" },
  { cmd: "chown", zh: "修改属主属组", eg: "chown -R www:www /var/www" },
  { cmd: "umask", zh: "设置新建文件默认权限掩码", eg: "umask 022" },
  { cmd: "tar", zh: "打包/解包", eg: "tar -zxvf pkg.tar.gz" },
  { cmd: "gzip", zh: "压缩/解压（单文件）", eg: "gzip -k file" },
  { cmd: "zip / unzip", zh: "ZIP 压缩与解压", eg: "unzip -O cp936 win.zip" },
  { cmd: "rsync", zh: "增量同步（可断点续传）", eg: "rsync -avz src/ user@host:/dst/" },
  { cmd: "scp", zh: "远程复制文件", eg: "scp -r dist/ user@host:/var/www/" },
  { cmd: "ssh", zh: "远程登录", eg: "ssh -p 2222 user@host" },
  { cmd: "ssh-keygen", zh: "生成密钥对", eg: "ssh-keygen -t ed25519" },
  { cmd: "ssh-copy-id", zh: "把公钥部署到远端", eg: "ssh-copy-id user@host" },
  { cmd: "curl", zh: "发起 HTTP 请求", eg: "curl -sSL -o f.zip https://x/y.zip" },
  { cmd: "wget", zh: "下载文件（支持断点续传）", eg: "wget -c https://x/big.iso" },
  { cmd: "ping", zh: "连通性测试（ICMP）", eg: "ping -c 4 8.8.8.8" },
  { cmd: "traceroute", zh: "路由追踪", eg: "traceroute example.com" },
  { cmd: "mtr", zh: "持续路由质量分析", eg: "mtr -rw example.com" },
  { cmd: "ss", zh: "查看套接字/端口（替代 netstat）", eg: "ss -tlnp" },
  { cmd: "netstat", zh: "查看网络连接（旧）", eg: "netstat -ano | grep 80" },
  { cmd: "lsof", zh: "查看进程打开的文件/端口", eg: "lsof -i :8080" },
  { cmd: "nc", zh: "端口探测 / 临时监听", eg: "nc -zv host 443" },
  { cmd: "telnet", zh: "手动测试端口连通性", eg: "telnet host 25" },
  { cmd: "ip", zh: "现代网络配置命令", eg: "ip addr show" },
  { cmd: "ifconfig", zh: "传统网卡查看（旧）", eg: "ifconfig eth0" },
  { cmd: "route", zh: "查看/设置路由表", eg: "route -n" },
  { cmd: "dig", zh: "DNS 查询（详细）", eg: "dig +short example.com A" },
  { cmd: "nslookup", zh: "DNS 查询（交互）", eg: "nslookup example.com" },
  { cmd: "host", zh: "简洁 DNS 查询", eg: "host -t MX example.com" },
  { cmd: "iptables", zh: "IPv4 防火墙规则", eg: "iptables -L -n -v" },
  { cmd: "firewall-cmd", zh: "firewalld 管理", eg: "firewall-cmd --add-port=80/tcp --permanent" },
  { cmd: "ufw", zh: "Ubuntu 简易防火墙", eg: "ufw allow 443" },
  { cmd: "free", zh: "查看内存使用", eg: "free -h" },
  { cmd: "vmstat", zh: "系统性能统计", eg: "vmstat 1 5" },
  { cmd: "iostat", zh: "磁盘 I/O 统计", eg: "iostat -x 1" },
  { cmd: "sar", zh: "历史性能数据", eg: "sar -u 1 3" },
  { cmd: "uptime", zh: "运行时长与平均负载", eg: "uptime" },
  { cmd: "who / w", zh: "查看当前登录用户", eg: "w" },
  { cmd: "last", zh: "登录历史", eg: "last -n 20" },
  { cmd: "sudo", zh: "以其他身份执行", eg: "sudo -u www ls" },
  { cmd: "su", zh: "切换用户", eg: "su - deploy" },
  { cmd: "passwd", zh: "修改密码", eg: "passwd user" },
  { cmd: "useradd", zh: "新增用户", eg: "useradd -m -s /bin/bash dev" },
  { cmd: "usermod", zh: "修改用户属性", eg: "usermod -aG docker dev" },
  { cmd: "groupadd", zh: "新增用户组", eg: "groupadd deploy" },
  { cmd: "id", zh: "查看用户 UID/GID 与组", eg: "id www" },
  { cmd: "env / export", zh: "查看/设置环境变量", eg: "export PATH=$PATH:/opt/bin" },
  { cmd: "alias", zh: "命令别名", eg: "alias ll='ls -alh'" },
  { cmd: "history", zh: "命令历史", eg: "history | grep ssh" },
  { cmd: "echo", zh: "输出文本", eg: "echo -e \"a\\nb\"" },
  { cmd: "printf", zh: "格式化输出", eg: "printf '%s\\n' a b" },
  { cmd: "date", zh: "显示/设置时间", eg: "date '+%F %T'" },
  { cmd: "timedatectl", zh: "时区与时间同步", eg: "timedatectl set-timezone Asia/Shanghai" },
  { cmd: "cal", zh: "显示日历", eg: "cal -y 2026" },
  { cmd: "md5sum / sha256sum", zh: "校验文件摘要", eg: "sha256sum image.iso" },
  { cmd: "basename / dirname", zh: "取文件名/目录名", eg: "basename /a/b/c.txt" },
  { cmd: "realpath", zh: "输出绝对路径", eg: "realpath ./x" },
  { cmd: "readlink", zh: "读取符号链接目标", eg: "readlink -f link" },
  { cmd: "seq", zh: "生成数字序列", eg: "seq 1 2 10" },
  { cmd: "shuf", zh: "随机打乱行", eg: "shuf -n 1 list.txt" },
  { cmd: "tee / xargs / watch", zh: "常用管道辅助", eg: "watch -n 2 df -h" },
  { cmd: "nano / vi / vim", zh: "终端文本编辑器", eg: "vim /etc/hosts" },
  { cmd: "screen / tmux", zh: "会话保持（断线不丢）", eg: "tmux new -s work" },
  { cmd: "apt / yum / dnf", zh: "包管理器", eg: "apt install -y curl" },
  { cmd: "docker", zh: "容器管理", eg: "docker ps -a" },
  { cmd: "docker compose", zh: "编排多容器", eg: "docker compose up -d" },
  { cmd: "kubectl", zh: "Kubernetes 操作", eg: "kubectl get pods -A" },
  { cmd: "git", zh: "版本控制", eg: "git log --oneline -10" },
  { cmd: "redis-cli", zh: "Redis 客户端", eg: "redis-cli -h 127.0.0.1 info" },
  { cmd: "mysql", zh: "MySQL 客户端", eg: "mysql -uroot -p -e \"show databases\"" },
  { cmd: "psql", zh: "PostgreSQL 客户端", eg: "psql -U postgres -l" },
  { cmd: "openssl", zh: "证书与加密工具", eg: "openssl s_client -connect x:443" },
];
