// 从 dev-toolbox src/data/reference.ts 同步；改数据时两边一起改。
export interface HttpHeaderEntry {
  name: string
  dir: string
  zh: string
}

export const httpHeaderEntries: HttpHeaderEntry[] = [
  { name: 'Host', dir: '请求', zh: '目标主机与端口；HTTP/1.1 起必填' },
  { name: 'User-Agent', dir: '请求', zh: '客户端标识；很多 API 会按它做拦截或限流' },
  { name: 'Accept', dir: '请求', zh: '可接受的响应类型，如 text/html,application/json' },
  { name: 'Accept-Encoding', dir: '请求', zh: '可接受的压缩方式，如 gzip, br, zstd' },
  { name: 'Accept-Language', dir: '请求', zh: '期望语言，如 zh-CN,zh;q=0.9' },
  { name: 'Accept-Charset', dir: '请求', zh: '可接受的字符集（已基本废弃）' },
  { name: 'Authorization', dir: '请求', zh: '凭证，如 Bearer <token> 或 Basic <base64>' },
  { name: 'Cookie', dir: '请求', zh: '客户端携带的 Cookie' },
  { name: 'Referer', dir: '请求', zh: '来源页面地址；可用于防盗链与来源分析' },
  { name: 'Origin', dir: '请求', zh: '跨域请求的来源；CORS 校验依据' },
  { name: 'Content-Type', dir: '请求/响应', zh: '实体媒体类型，如 application/json; charset=utf-8' },
  { name: 'Content-Length', dir: '请求/响应', zh: '实体字节数' },
  { name: 'Content-Encoding', dir: '请求/响应', zh: '实体的压缩编码' },
  { name: 'Content-Disposition', dir: '响应', zh: 'inline 直接展示 / attachment 触发下载并可指定文件名' },
  { name: 'Content-Range', dir: '响应', zh: '分片响应覆盖的字节范围' },
  { name: 'Content-Security-Policy', dir: '响应', zh: 'CSP，限制资源加载来源，防 XSS' },
  { name: 'Cache-Control', dir: '请求/响应', zh: '缓存策略，如 no-cache / max-age=3600' },
  { name: 'ETag', dir: '响应', zh: '资源版本指纹，配合 If-None-Match 做协商缓存' },
  { name: 'Last-Modified', dir: '响应', zh: '资源最后修改时间，配合 If-Modified-Since' },
  { name: 'If-None-Match', dir: '请求', zh: '带上本地 ETag，未变则返回 304' },
  { name: 'If-Modified-Since', dir: '请求', zh: '带上本地时间，未变则返回 304' },
  { name: 'If-Match', dir: '请求', zh: '乐观锁：只有 ETag 匹配才执行' },
  { name: 'Expires', dir: '响应', zh: '绝对过期时间（HTTP/1.0 遗留，优先级低于 Cache-Control）' },
  { name: 'Age', dir: '响应', zh: '该响应在缓存中已存活的秒数' },
  { name: 'Date', dir: '响应', zh: '响应生成时间' },
  { name: 'Server', dir: '响应', zh: '服务端软件标识；建议在生产环境隐藏' },
  { name: 'Via', dir: '响应', zh: '经过的代理链' },
  { name: 'Location', dir: '响应', zh: '重定向目标地址，或 201 创建后的资源地址' },
  { name: 'Set-Cookie', dir: '响应', zh: '下发 Cookie；可带 HttpOnly / Secure / SameSite' },
  { name: 'Strict-Transport-Security', dir: '响应', zh: 'HSTS，强制浏览器后续只用 HTTPS' },
  { name: 'X-Frame-Options', dir: '响应', zh: '是否允许被 iframe 嵌入，防点击劫持' },
  { name: 'X-Content-Type-Options', dir: '响应', zh: '设为 nosniff 禁止浏览器猜测类型' },
  { name: 'X-XSS-Protection', dir: '响应', zh: '旧版浏览器 XSS 过滤开关（已被 CSP 取代）' },
  { name: 'Referrer-Policy', dir: '响应', zh: '控制 Referer 的发送粒度' },
  { name: 'Permissions-Policy', dir: '响应', zh: '精细化授权摄像头/麦克风/定位等能力' },
  { name: 'Access-Control-Allow-Origin', dir: '响应', zh: 'CORS：允许的来源；不能与 credentials 同时用 *' },
  { name: 'Access-Control-Allow-Methods', dir: '响应', zh: 'CORS：允许的方法' },
  { name: 'Access-Control-Allow-Headers', dir: '响应', zh: 'CORS：允许的自定义请求头' },
  { name: 'Access-Control-Allow-Credentials', dir: '响应', zh: 'CORS：是否允许携带 Cookie' },
  { name: 'Access-Control-Max-Age', dir: '响应', zh: 'CORS 预检结果缓存秒数' },
  { name: 'Vary', dir: '响应', zh: '缓存键的附加维度，如 Accept-Encoding' },
  { name: 'Transfer-Encoding', dir: '响应', zh: '传输编码，chunked 表示分块传输' },
  { name: 'Connection', dir: '请求/响应', zh: '连接控制，keep-alive 复用长连接' },
  { name: 'Upgrade', dir: '请求/响应', zh: '请求协议升级，如 websocket' },
  { name: 'TE', dir: '请求', zh: '可接受的传输编码（配合 chunked 的 trailers）' },
  { name: 'Range', dir: '请求', zh: '请求部分内容，如 bytes=0-1023' },
  { name: 'Retry-After', dir: '响应', zh: '多久后可重试，常与 429/503 搭配' },
  { name: 'WWW-Authenticate', dir: '响应', zh: '认证方式质询，配合 401' },
  { name: 'Forwarded / X-Forwarded-For', dir: '请求', zh: '原始客户端 IP；代理转发时写入' },
  { name: 'X-Forwarded-Proto', dir: '请求', zh: '原始协议（http/https），用于生成正确回跳地址' },
  { name: 'X-Request-Id', dir: '请求/响应', zh: '链路追踪 ID' },
  { name: 'CF-Connecting-IP', dir: '请求', zh: 'Cloudflare 回源时携带的真实客户端 IP' },
];
