/**
 * 搜索别名表。
 *
 * 为什么需要
 * ------------------------------------------------------------------
 * 工具的 keywords 是英文的（来自上游项目），中文用户更习惯搜「编码」「时间戳」
 * 「美化」这类词。工具标题虽然已经中文化，但很多是直译，和用户脑子里的叫法
 * 对不上：比如用户搜「格式化 JSON」，标题是「JSON美化和格式化」，勉强能命中；
 * 但搜「压缩 JSON」就完全找不到「JSON 压缩」以外的说法。
 *
 * 这里按工具路由补一批中文同义词和场景词，首页搜索和 Ctrl+K 命令面板共用。
 *
 * key 是工具路由（与 defineTool 里的 path 一致）。
 */

export const ALIASES: Record<string, string[]> = {
  '/ascii-text-drawer': ['艺术字', 'ascii', '字符画', '大字', 'banner', '花体字'],
  '/base-converter': ['进制', '进制转换', '十六进制', '二进制', '八进制', 'hex', '换算'],
  '/base64-file-converter': ['文件转base64', '图片转base64', 'base64', 'data uri', '内联', '编码'],
  '/base64-string-converter': ['base64', '编码', '解码', 'b64', '明文', '加密'],
  '/basic-auth-generator': ['basic auth', '认证', '鉴权', 'authorization', '用户名密码', '请求头'],
  '/bcrypt': ['bcrypt', '哈希', '散列', '密码', '加密', '校验密码', 'hash'],
  '/benchmark-builder': ['基准测试', '性能', '耗时', 'benchmark', '跑分', '对比速度'],
  '/bip39-generator': ['助记词', 'bip39', '钱包', '密钥', 'mnemonic', '种子'],
  '/camera-recorder': ['摄像头', '拍照', '录像', '相机', 'camera', '录屏'],
  '/case-converter': ['大小写', '驼峰', 'camel', 'snake', '命名', '转换', '下划线', 'kebab'],
  '/chmod-calculator': ['chmod', '权限', 'linux', 'rwx', '755', '文件权限'],
  '/chronometer': ['计时器', '秒表', '倒计时', '耗时', 'timer', '打点'],
  '/color-converter': ['颜色', '色值', 'rgb', 'hex', 'hsl', '取色', '调色'],
  '/crontab-generator': ['cron', '定时任务', '计划任务', 'crontab', '表达式', '调度'],
  '/date-converter': ['时间戳', '时间', '日期', 'unix', 'timestamp', '格式化时间'],
  '/device-information': ['设备信息', '屏幕', '分辨率', 'user agent', '浏览器信息', 'ua'],
  '/docker-run-to-docker-compose-converter': ['docker', 'compose', '容器', '转换', 'yml'],
  '/email-normalizer': ['邮箱', '邮件', 'email', '去重', '清洗', '归一化'],
  '/emoji-picker': ['表情', 'emoji', '颜文字', 'unicode', 'emoji复制'],
  '/encryption': ['加密', '解密', 'aes', 'des', '对称加密', '密码', 'cipher'],
  '/eta-calculator': ['预计时间', '剩余时间', 'eta', '进度', '完成时间'],
  '/git-memo': ['git', '命令', '速查', '备忘', 'cheatsheet', '版本控制'],
  '/hash-text': ['哈希', 'md5', 'sha1', 'sha256', '摘要', '散列', 'hash', '签名'],
  '/hmac-generator': ['hmac', '签名', '密钥', '哈希', '接口签名', '验签'],
  '/html-entities': ['html', '转义', '实体', '反转义', 'escape', '特殊字符'],
  '/html-wysiwyg-editor': ['富文本', '编辑器', 'html', '所见即所得', 'wysiwyg', '排版'],
  '/http-status-codes': ['状态码', 'http', '404', '500', 'status', '响应码'],
  '/iban-validator-and-parser': ['iban', '银行', '账号', '校验', '汇款'],
  '/ipv4-address-converter': ['ip', 'ipv4', '地址转换', '十进制', '二进制', '换算'],
  '/ipv4-range-expander': ['ip', 'cidr', '网段', '范围', '掩码', '防火墙'],
  '/ipv4-subnet-calculator': ['子网', 'cidr', '网段', '掩码', 'ip', 'subnet', '主机数'],
  '/ipv6-ula-generator': ['ipv6', 'ula', '内网地址', '生成', 'rfc4193'],
  '/json-diff': ['json', '对比', '差异', 'diff', '比较', '变更'],
  '/json-minify': ['json', '压缩', 'minify', '一行', '精简', '去空格'],
  '/json-prettify': ['json', '格式化', '美化', '缩进', 'pretty', '整理'],
  '/json-to-csv': ['json', 'csv', '表格', 'excel', '转换', '导出'],
  '/json-to-toml': ['json', 'toml', '转换', '配置'],
  '/json-to-xml': ['json', 'xml', '转换', '报文'],
  '/json-to-yaml-converter': ['json', 'yaml', 'yml', '转换', '配置'],
  '/jwt-parser': ['jwt', 'token', '解析', '解码', '令牌', '登录'],
  '/keycode-info': ['键码', 'keycode', '快捷键', '键盘', '按键', 'ascii码'],
  '/list-converter': ['列表', '排序', '去重', '批量', '前缀', '后缀', '反转'],
  '/lorem-ipsum-generator': ['占位', '假文', 'lorem', '示例文本', '填充'],
  '/mac-address-generator': ['mac', '物理地址', '生成', '网卡', '批量'],
  '/mac-address-lookup': ['mac', '厂商', '查询', 'oui', '设备', '网卡'],
  '/markdown-to-html': ['markdown', 'md', 'html', '转换', '文档', '渲染'],
  '/math-evaluator': ['计算', '算式', '数学', '表达式', '求值', '函数'],
  '/mime-types': ['mime', 'content-type', '扩展名', '文件类型', '后缀'],
  '/numeronym-generator': ['缩写', 'i18n', 'numeronym', '简写'],
  '/og-meta-generator': ['og', 'meta', '分享', '社交', '卡片', '缩略图', 'open graph'],
  '/otp-generator': ['otp', '验证码', '两步验证', '2fa', 'totp', '动态口令'],
  '/password-strength-analyser': ['密码', '强度', '安全', '破解', '强度检测', '口令'],
  '/pdf-signature-checker': ['pdf', '签名', '校验', '签章', '验签'],
  '/percentage-calculator': ['百分比', '比例', '增幅', '占比', 'percent'],
  '/phone-parser-and-formatter': ['手机号', '电话', '号码', '归属地', '格式化', '区号'],
  '/qrcode-generator': ['二维码', 'qr', '扫码', '生成', 'qrcode'],
  '/random-port-generator': ['端口', '随机', 'port', '生成'],
  '/regex-memo': ['正则', 'regex', '速查', '备忘', '表达式', '语法'],
  '/regex-tester': ['正则', 'regex', '测试', '匹配', '校验', '表达式'],
  '/roman-numeral-converter': ['罗马数字', 'roman', '数字', '转换'],
  '/rsa-key-pair-generator': ['rsa', '公钥', '私钥', '密钥对', 'pem', '非对称'],
  '/safelink-decoder': ['safelink', 'outlook', '安全链接', '解码', '还原', '邮件'],
  '/slugify-string': ['slug', 'url', '文件名', '短横线', '别名', '安全字符串'],
  '/sql-prettify': ['sql', '格式化', '美化', '缩进', '查询', '数据库'],
  '/string-obfuscator': ['打码', '遮蔽', '脱敏', '混淆', '掩码', '隐藏'],
  '/svg-placeholder-generator': ['svg', '占位图', 'placeholder', '骨架', '图片'],
  '/temperature-converter': ['温度', '摄氏度', '华氏度', '开尔文', '换算'],
  '/text-diff': ['对比', '差异', 'diff', '文本比较', '变更'],
  '/text-statistics': ['字数', '统计', '字符数', '字节', '词数', '计数'],
  '/text-to-binary': ['二进制', 'binary', 'ascii', '转换', '01'],
  '/text-to-nato-alphabet': ['音标', '字母', 'nato', '拼写', '对讲'],
  '/text-to-unicode': ['unicode', '码点', '编码', '转义', '字符'],
  '/token-generator': ['随机', '字符串', 'token', '口令', '邀请码', '生成'],
  '/toml-to-json': ['toml', 'json', '转换', '配置'],
  '/toml-to-yaml': ['toml', 'yaml', '转换', '配置'],
  '/ulid-generator': ['ulid', 'uuid', '唯一id', '生成', '有序', '主键'],
  '/url-encoder': ['url', '编码', '解码', '百分号', '转义', 'encode', '参数'],
  '/url-parser': ['url', '解析', '拆解', '参数', 'query', '链接'],
  '/user-agent-parser': ['ua', 'user agent', '浏览器', '识别', '解析', '系统'],
  '/uuid-generator': ['uuid', 'guid', '唯一', 'id', '生成', '随机'],
  '/wifi-qrcode-generator': ['wifi', '二维码', '无线', '扫码连网', '密码'],
  '/xml-formatter': ['xml', '格式化', '美化', '缩进', '报文'],
  '/xml-to-json': ['xml', 'json', '转换', '报文'],
  '/yaml-prettify': ['yaml', '格式化', '美化', 'yml', '缩进'],
  '/yaml-to-json-converter': ['yaml', 'json', '转换', 'yml', '配置'],
  '/yaml-to-toml': ['yaml', 'toml', '转换', 'yml', '配置'],
}
